
package Interface;

import EstructuraDeVehiculos.listaDeVehiculos;

public class VentanaRegistrarVehiculo extends javax.swing.JFrame {
    listaDeVehiculos vehiculos = new listaDeVehiculos ();
    String placa;
    String marca;
    String modelo;
    String año;
    String color;
    String cilindrada;
    String combustible;
    String pasajeros;
    double precioXdia;
    String extras;
    String status;

    /**
     * Creates new form VentanaRegistrarVehiculo
     */
    public VentanaRegistrarVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRegistroDeVehículos = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblAño = new javax.swing.JLabel();
        txtAño = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblCilindrada = new javax.swing.JLabel();
        txtCilindrada = new javax.swing.JTextField();
        lblCombustible = new javax.swing.JLabel();
        txtCombustible = new javax.swing.JTextField();
        lblPasajeros = new javax.swing.JLabel();
        txtPasajeros = new javax.swing.JTextField();
        lblAlquilerXDia = new javax.swing.JLabel();
        txtAlquilerXDia = new javax.swing.JTextField();
        lblExtras = new javax.swing.JLabel();
        txtExtras = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 650));
        setMinimumSize(new java.awt.Dimension(900, 650));
        setPreferredSize(new java.awt.Dimension(900, 650));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRegistroDeVehículos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblRegistroDeVehículos.setForeground(new java.awt.Color(0, 0, 0));
        lblRegistroDeVehículos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistroDeVehículos.setText("Registro de Vehículos");
        jPanel1.add(lblRegistroDeVehículos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 900, -1));

        lblPlaca.setForeground(new java.awt.Color(0, 0, 0));
        lblPlaca.setText("Número de placa");
        jPanel1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 96, -1, -1));

        txtPlaca.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 93, 356, -1));

        lblMarca.setForeground(new java.awt.Color(0, 0, 0));
        lblMarca.setText("Marca");
        jPanel1.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 136, -1, -1));

        txtMarca.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 133, 356, -1));

        lblModelo.setForeground(new java.awt.Color(0, 0, 0));
        lblModelo.setText("Modelo");
        jPanel1.add(lblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 176, -1, -1));

        txtModelo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 173, 356, -1));

        lblAño.setForeground(new java.awt.Color(0, 0, 0));
        lblAño.setText("Año");
        jPanel1.add(lblAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 216, -1, -1));

        txtAño.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 213, 356, -1));

        lblColor.setForeground(new java.awt.Color(0, 0, 0));
        lblColor.setText("Color");
        jPanel1.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 256, -1, -1));

        txtColor.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 253, 356, -1));

        lblCilindrada.setForeground(new java.awt.Color(0, 0, 0));
        lblCilindrada.setText("Cilindrada");
        jPanel1.add(lblCilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 296, -1, -1));

        txtCilindrada.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCilindrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 293, 356, -1));

        lblCombustible.setForeground(new java.awt.Color(0, 0, 0));
        lblCombustible.setText("Combustible");
        jPanel1.add(lblCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 336, -1, -1));

        txtCombustible.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtCombustible, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 333, 356, -1));

        lblPasajeros.setForeground(new java.awt.Color(0, 0, 0));
        lblPasajeros.setText("Pasajeros");
        jPanel1.add(lblPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 376, -1, -1));

        txtPasajeros.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 373, 356, -1));

        lblAlquilerXDia.setForeground(new java.awt.Color(0, 0, 0));
        lblAlquilerXDia.setText("Alquiler por día");
        jPanel1.add(lblAlquilerXDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 416, -1, -1));

        txtAlquilerXDia.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtAlquilerXDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 413, 356, -1));

        lblExtras.setForeground(new java.awt.Color(0, 0, 0));
        lblExtras.setText("Extras");
        jPanel1.add(lblExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 456, -1, -1));

        txtExtras.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 453, 356, -1));

        btnRegistrar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 170, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        placa = txtPlaca.getText();
        marca = txtMarca.getText();
        modelo = txtModelo.getText();
        año = txtAño.getText();
        color = txtColor.getText();
        cilindrada = txtCilindrada.getText();
        combustible = txtCombustible.getText();
        pasajeros = txtPasajeros.getText();
        precioXdia = Double.parseDouble(txtMarca.getText());
        extras = txtExtras.getText();

        //vehiculos.registrarVehiculo(new vehiculo(placa,marca,modelo,año,color,cilindrada,combustible,pasajeros,precioXdia,extras));

    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistrarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistrarVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlquilerXDia;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCilindrada;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblCombustible;
    private javax.swing.JLabel lblExtras;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPasajeros;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblRegistroDeVehículos;
    private javax.swing.JTextField txtAlquilerXDia;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCilindrada;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCombustible;
    private javax.swing.JTextField txtExtras;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPasajeros;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
